Adiciona informações de usuários e bares seguidos
GoogolApp/googol-frontend pull request #72
Opened 2019-04-10 21:42 UTC by dnrocha1

2019-04-10 23:38 UTC, matheusps requested changes

2019-04-10 23:38 UTC, matheusps commented on src/_services/users.ts
> +                return user.following;
Não precisa do `return` se remover as chaves... `.map( user => user.following )`

2019-04-10 23:38 UTC, matheusps commented on src/_services/users.ts
> +                return bar.followingBars;
O mesmo vale aqui...

2019-04-10 23:38 UTC, matheusps commented on src/pages/User/following/bars-tab/bars-tab.scss
> +        font-size: 15px;
Essa regra não poderia estar só em `.placeholder` ?

2019-04-10 23:38 UTC, matheusps commented on src/pages/User/following/bars-tab/bars-tab.ts
> +        console.log(this.bars)
remover console

2019-04-10 23:38 UTC, matheusps commented on src/pages/User/following/following.html
> +  <ion-tabs tabsPlacement="top" style="margin-top: 45px;">
Esse `style` deveria ser uma classe css

2019-04-10 23:38 UTC, matheusps commented on src/pages/User/following/following.ts
> +      showPageBarCb: this.showPageBar.bind(this)
`showPageBar` já seria "bound" se fosse uma arrow function...eu acho 🤔

2019-04-11 03:01 UTC, dnrocha1 commented on src/pages/User/following/bars-tab/bars-tab.scss
> +        font-size: 15px;
Reutilizei o estilo de algum outro lugar, mas acho que esse `.placeholder` é aplicado pra algum estilo do próprio Ionic.

2019-04-11 03:08 UTC, dnrocha1 commented on src/pages/User/following/following.html
> +  <ion-tabs tabsPlacement="top" style="margin-top: 45px;">
Done

2019-04-11 03:08 UTC, dnrocha1 commented on src/pages/User/following/bars-tab/bars-tab.ts
> +        console.log(this.bars)
Done

2019-04-11 03:08 UTC, dnrocha1 commented on src/_services/users.ts
> +                return bar.followingBars;
Done

2019-04-11 03:08 UTC, dnrocha1 commented on src/_services/users.ts
> +                return user.following;
Done

2019-04-11 03:13 UTC, dnrocha1 commented on src/pages/User/following/following.ts
> +      showPageBarCb: this.showPageBar.bind(this)
:thinking:

2019-04-11 04:47 UTC, matheusps approved these changes

2019-04-11 04:48 UTC, merged